### ISSUE TITLE
Делать утреннее сообщение в чат

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#12]
В 7:00 бот должен постить сгенерированное сообщение в чат.

Что сообщение должно/может включать в себя:
1. Приветствие (желательно нагенерировать по-больше вариантов и выбирать на рандоме)
1. Температуру на день, желательно по нескольким отрезкам времени
1. Случайную картинку из каналов с котиками
1. Подборку нескольких заголовков новостей (?)
1. Ещё идеи?

Зачем:
- Создавать темы для обсуждения
- К утру чат засыпает, так что не будет мешать и внесет толику разнообразия 
- Милота
- Бикоз ви кэн

**Comment by uburuntu** [comment]
#6

**Comment by iglunchadze** [comment]
6. Какая-нибудь свежая ботва с arXiv

7:00 не рано?

**Comment by uburuntu** [comment]
А когда? Я на первых курсах в 7 часов уже угрюмо шел к остановке.

**Comment by uburuntu** [comment]
Первый заход: d411ddd

На данный момент из фич есть только Котик дня.

**Comment by uburuntu** [comment]
Погода теперь есть.

Осталось нагенерировать разнообразных приветствий и т.п.
