### ISSUE TITLE
Сделать команду /clean для очистки сообщений бота

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#13]
После обстрелов командо-пушками довольно непросто вычистить чат.
Предлагается команда для авто-зачистки вызовов команд и своих сообщений за последние N минут.
Для вызова нужны права админа.

Тег future feature из-за относительной сложности реализации.
Вариант реализации нужно обсудить.

**Comment by arvego** [comment]
Fixed.

**Comment by uburuntu** [comment]
Еще не всё сделано.

Надо добавить:
- защита от "дурака" и обрезать огромные числа
- удаление до реплая
- удаление по времени, а не по количеству сообщений
- удаление вызовов команд

**Comment by uburuntu** [comment]
Осталось:
- удаление вызовов команд и их ответов -- изначальная цель
- (необязательно) удаление до реплая
- (необязательно) удаление по времени, а не по количеству сообщений

**Comment by arvego** [comment]
Задача решена.
