### ISSUE TITLE
Заменить memeSurprise на более качественную версию

### ISSUE THREAD

**Issue by iglunchadze** [arvego/mm-randbot#14]
Вот на такую
https://media.giphy.com/media/HP5dest4oOHf2/giphy.mp4

**Comment by arvego** [comment]
Fixed. Только не удаляй, пожалуйста, это сообщение -- https://t.me/mechmath/126325 Он из него берёт уже загруженную гифку, чтобы было быстрее.

**Comment by uburuntu** [comment]
Лол, удалил.

**Comment by arvego** [comment]
https://t.me/mechmath/127603 Не делай так больше никогда.

**Comment by uburuntu** [comment]
@arvego ☺️
