### ISSUE TITLE
Сделать поддержку экспорта публикаций в Facebook

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#15]
У мехмата есть страница на фейсбуке.
Долгое время перебирал существующие реализации экспорта постов vk -> facebook.

На данный момент подходящих реализаций не существует, а используемый вариант стремный.

Поэтому предлагаю добавить в бота при появлении постов вк, экспортить их.

**Comment by EzAccount** [comment]
https://stackoverflow.com/a/39248356/6186211

Step-by-step guide on never-expire page token.

**Comment by arvego** [comment]
commit 75b10485f4e504c9e450ccb79b4d71e6f4d82d61
Почти решено. Нужно активное тестирование.
