### ISSUE TITLE
Не отображается видео при постинге с вк

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#19]
![](https://i.imgur.com/TZhIabl.jpg)

**Comment by uburuntu** [comment]
Предлагается парсить ссылку на видео и, включая веб-превью, кидать ее в пост.
Поскольку ТГ сам хорошо отображает видео.

**Comment by uburuntu** [comment]
Теперь, как минимум, появляется ссылка.
Если повезет, то видео будет доступно как веб_превью.

**Comment by arvego** [comment]
Fixed for now. :)
