### ISSUE TITLE
Отправлять результат /wf как документ, если изображение большое

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#2]
Надо подобрать максимальную высоту изображения, после которой смотреть пережатый файл уже неудобно

**Comment by EzAccount** [comment]
Можно просто резать output в несколько изображений

**Comment by arvego** [comment]
@EzAccount Он на самом сервере делает картинку.

**Comment by uburuntu** [comment]
@arvego Картинки сильно спамят "вложения", поэтому надо стремиться к уменьшению сгенеренных картинок как тут, так и в других командах

**Comment by arvego** [comment]
Done.
