### ISSUE TITLE
Предусмотреть защиту от флудеров

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#3]
Проблема: люди спамят командами, тыкая одно и то же много раз

Варианты решения предлагайте.

Мои первые мысли:
- На 4 вызов одной команды от одного и того же человека подряд -- перестать отвечать ему
- Сделать таймауты на спамящие команды. К примеру, перестать отвечать, если /kek-нули больше 60 раз за последний час

**Comment by arvego** [comment]
Реализовал по второму пункту – если за час все пользователи супергруппы прокекали больше 60 (задаётся в data.py) раз, то до истечения этого часа /kek не будет реагировать на запросы.
Для ЛС такого ограничения нет.
