### ISSUE TITLE
Добавить поддержку звука в /kek

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#30]
Поддержку можно реализовать аналогично стикерам, т.к. звуки также имеют свои id, к примеру:

`<audio>AwADAgADaAADkiGwStG3CA2iWgJXAg`

**Comment by uburuntu** [comment]
`<audio>AwADAgADpQADuBGpSjHyuHrqZvmeAg`

**Comment by arvego** [comment]
Fixed.
