### ISSUE TITLE
Сделать /d6 более интерактивным

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#4]
Добавить аргумент (число от 1 до 10) к команде, которое указывает сколько костей кинуть:
> /d6
⚃

> /d6 4
⚀ ⚂ ⚅ ⚃

Добавить сумму и максимум костей:
> /d6
⚃ = 4 (6)

> /d6 4
⚀ + ⚂ + ⚅ + ⚃ = 14 (24)

**Comment by arvego** [comment]
Сделано.
Также добавил команду `/dn <1> <2>`, которая генерует рандомное целое число от 0 до <1> <2> раз и кидает сумму:
`/dn 12 3
2 + 11 + 3 = 16  (36)`
