### ISSUE TITLE
Добавить счетчик хромосом /disa

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#5]
1. Создать группу вк
2. Добавить команду в бота, которая проверяет последний пост, добавляет 1 и создает новый пост

**Comment by uburuntu** [comment]
https://vk.com/disa_count

**Comment by uburuntu** [comment]
@uburuntu https://vk.com/dev/wall.post

**Comment by EzAccount** [comment]
Осталось:
1. Проверка существует ли пост от сегодняшего дня - если нет, обнулить и создать новый пост.
2. ? Красивый пост вк ?

**Comment by uburuntu** [comment]
На каждое 20е можно к сообщению приписывать группу: https://vk.com/disa_count, чтоб чекали

**Comment by EzAccount** [comment]
Artemiy Gevorkov:
Нужно сделать ещё так, чтобы он прибавлял к уже имеющемуся числу каждый час, а не заменял.
Аесли день новый, то создавал бы новый пост.

**Comment by arvego** [comment]
Fixed. Теперь постит и в чат, и в ВК с периодом не менее часа.
