### ISSUE TITLE
Вместо пиклинга, хранить генерируемые данные в embedded-СУБД

### ISSUE THREAD

**Issue by gurland** [arvego/mm-randbot#57]
Начать переход на хранение данных в SQLite. Начать с реализации учета всех пользователей в чате.
Когда получаем `new_chat_participant` - добавляем пользователя в базу, когда получаем `left_chat_participant` удаляем (или меняем статус в отдельном поле в базе).
В дальнейшем полностью заменить способ хранения данных на хранение в SQLite. Для легкого общения, а также благодаря полному хэндлингу логистики предлагаю ORM Peewee.
### Планы:
- Сделать таск #56, обкатав систему
- С помощью контрибуторов найти остальные генерируемые данные и переписать старый код

**Comment by uburuntu** [comment]
В идеале хотелось бы, чтобы выбранная БД могла минимумом действий стать сетевой (https://github.com/arvego/mm-randbot/issues/38) для быстрого перезапуска на любой машине

**Comment by gurland** [comment]
Для быстрого перезапуска одного конкретного бота с настроенной сетевой базой. Для деплоя нового бота это будет сложнее в разы.

**Comment by uburuntu** [comment]
Почему?
Для деплоя будут указаны данные для доступа к серверу. Без необходимости копировать из предыдущего места деплоя.

**Comment by gurland** [comment]
- Это привязка к определенному сервису. Если юзер захочет использовать другой сервис или локальную базу - нужно будет помучится для переноса.
- Это совсем не отказывоустойчивое решение
- Это сильно медленее обычного запроса на диск (на самом деле сетевые стораджи быстрее, но не в нашем случае. Настройка нормальной распределенной системы стоит денег). Представь что бот запущен где-то у местячкового провайдера где-то на Востоке России, например. Огромные пинги к ДЦ с базой в Москве например. Пользователю придется долго ждать + блокируется тред. 

Абсолютно, как я считаю не нужное решение пока что. Распределение любой системы по теории CAP добавляет третее свойство за которым нужно следить - устойчивость к разделению, это дополнительная проблема, представь что запрос от сервера с бизнес-логикой к БД пропадет, дальше идет таймаут огромный с блокировкой, а потом недоступность базы. И все запросы будут улетать в таймаут. 
Я считаю что это создание лишних проблем на ровном месте.

**Comment by numberZero** [comment]
@gurland Полностью согласен. Удалённая база — звучит круто, но предлагаемое использование вообще-то попахивает резервным копированием, а это немножко не то же самое, что повседневная работа.

**Comment by uburuntu** [comment]
Хорошо, у меня есть кое-какие наработки по бекапингу для другого бота, перенесу. Может хватит и этого.

**Comment by gurland** [comment]
#59
