### ISSUE TITLE
Обновить хендлер new_group_member

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#7]
1. Убрать автоматический вызов rules (а то правда много текста)
1. Поменять сообщение на:
> Приветствую, %username_вступившего%!
Если здесь впервые, то ознакомься с правилами -- /rules, и представься, если несложно.

Future feature: добавить рандомное приветствие вместо первого слова. По типу: Aloha, %user%! или Вечер в хату, %user%!
Отдельный файл не надо, можно массивчик бахнуть с приветствиями.

**Comment by arvego** [comment]
Done.
