### ISSUE TITLE
Улучшить вид публикаций из группы

### ISSUE THREAD

**Issue by uburuntu** [arvego/mm-randbot#8]
На данный момент для репостов пишется небольшая шапка:

> Репост из группы [День открытых дверей Техносферы](https://vk.com/dodsphere):
:bell:Приходите завтра на День открытых дверей Техносферы! 

Предлагается модифицировать ее и добавить аналогичную для постов, чтобы у публикаций из группы был единый вид.
Конкретнее:

1. [x] Добавить шапку к "постам"
2. [x] Сделать ссылку на саму публикацию в слове "Пост" и "Репост". Ссылку на группу при репосте нужно оставить.

Таким образом получится такое.

Пример для "постов":

> [Пост](https://vk.com/wall-1441_9468) в группе [Мехмат МГУ](https://vk.com/msu_mechmath):
Коллективными усилиями нашего телеграм-чата https://t.me/mechmath создан первый в истории полезный бот: https://t.me/algebrach_bot.

Пример для репостов:

> [Репост](https://vk.com/wall-1441_9496) из группы [День открытых дверей Техносферы](https://vk.com/dodsphere):
:bell:Приходите завтра на День открытых дверей Техносферы!

**Comment by iglunchadze** [comment]
Закрыто коммитом da8de6b, выйдет в прод в ближайшем релизе.
